#!/usr/bin/python
#################################################################
#
#    file: get_variable.py
#   usage: ./get_variable.py
#   brief:
#  author: ***
#   email: ***
# created: 2017-11-24 17:36:15
#
#################################################################
import tensorflow as tf

def conv_relu(input, kernel_shape, bias_shape):
    weights = tf.get_variable("weights", kernel_shape,
                              initializer=tf.random_normal_initializer())
    biases = tf.get_variable("biases", bias_shape,
                             initializer=tf.constant_intializer(0.0))
    conv = tf.nn.conv2d(input, weights,
                        strides=[1, 1, 1, 1], padding='SAME')
    return tf.nn.relu(conv + biases)

def my_image_filter(input_images):
    with tf.variable_scope("conv1"):#Variables created here will be named "conv1/weights", "conv1/biases".
        relu1 = conv_relu(input_images, [5, 5, 32, 32], [32])
    with tf.variable_scope("conv2"):# Variables created here will be named "conv2/weights", "conv2/biases".
        return conv_relu(relu1, [5, 5, 32, 32], [32])
image1 = [1,2,3,43,4]
image2 = [3,4,5,6,7,7]
result1 = my_image_filter(image1)
result2 = my_image_filter(image2)
